### PR TITLE
bump: Gradle to latest version always

### PR DESCRIPTION
**Pull request by mochadwi**
There is no known issue: https://docs.gradle.org/7.3/release-notes.html#known-issues

### CODE REVIEW

**Comment by mochadwi** [comment]
needs review and approval: @sakti @adesamp @anangkur

**Comment by mochadwi** [comment]
bump: @sakti @adeds @anangkur

**Review by sakti — APPROVED** [review]
LGTM

**Comment by adeds** [comment]
LGTM

**Comment by mochadwi** [comment]
thanks folks! there's a signficant improvement recent Gradle 7.4 release see in here:

**Comment by mochadwi** [comment]
https://twitter.com/vRallev/status/1493829721477431299?t=refQLvAspbZ99JwX7omzGA&s=19

**Review by anangkur — COMMENTED** [review]
can't wait to build!

**Pull request merged**
